name: Update README

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          GH_USERNAME: TaQuangKhoi
          COMMIT_NAME: Tạ Quang Khôi
          COMMIT_MSG: ⚡ Đỗ Quyên Update README with the recent activity 
          COMMIT_EMAIL: khoi0941@gmail.com
